import {
  BoardBaseRequest,
  ConfirmShareTokenRequest,
  CreateBoardRequest,
  CreateColumnRequest,
  CreateShareTokenRequest,
  CreateTicketRequest,
  EditBoardRequest,
  EditColumnRequest,
  EditTicketRequest,
  GetBoardRequest,
  GetBoardsWithPaginationRequest,
  GetColumnRequest,
  GetTicketRequest,
  RemoveBoardRequest,
  RemoveColumnRequest,
  RemoveTicketRequest,
  UpdateBoardRequest,
} from "board-contracts/lib/board/types/request.type";

export type {
  BoardBaseRequest,
  ConfirmShareTokenRequest,
  CreateBoardRequest,
  CreateColumnRequest,
  CreateShareTokenRequest,
  CreateTicketRequest,
  EditBoardRequest,
  EditColumnRequest,
  EditTicketRequest,
  GetBoardRequest,
  GetBoardsWithPaginationRequest,
  GetColumnRequest,
  GetTicketRequest,
  RemoveBoardRequest,
  RemoveColumnRequest,
  RemoveTicketRequest,
  UpdateBoardRequest,
};
